//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoteCuoiKyWF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Note
    {
        public int id { get; set; }
        public string tieude { get; set; }
        public string noidung { get; set; }
        public DateTime createdatetime { get; set; }
        public DateTime lasttimesave { get; set; }
        public string tag { get; set; }
    }
}
